artifacts_root: artifacts

# Cryptocurrency Configuration
cryptocurrencies:
  - solana

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://api.coingecko.com/api/v3  # CoinGecko API base URL
  local_data_file: artifacts/data_ingestion/crypto_data.csv
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/crypto_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/crypto_data.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

deep_model_trainer:
  root_dir: artifacts/deep_model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: deep_model.pth



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

deep_model_evaluation:
  root_dir: artifacts/deep_model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/deep_model_trainer/best_deep_model.pth
  scaler_path: artifacts/deep_model_trainer/scaler.joblib
  model_config_path: artifacts/deep_model_trainer/model_config.json
  metric_file_name: artifacts/deep_model_evaluation/metrics.json

feature_engineering:
  root_dir: artifacts/feature_engineering
  metadata_path: artifacts/feature_metadata.json
  enable_validation: true
  drift_threshold: 3.0
